version: '3'

services:
  app:
    build: .
    container_name: go-api-app
    ports:
      - "8080:8080"
    environment:
      TZ: "America/Sao_Paulo"
    depends_on:
      - redis
      - elasticsearch

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.11.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
