version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      TZ: "America/Sao_Paulo"
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"